In [5]:
import pandas as pd

In [6]:
pre = pd.read_csv('../therm/top_brightness.csv', header=None)
pre.head()

,0,1,2,3,4
0,NaN,id,struct,brightness,sequence
1,6808718.0,1379211,"avGFP_2WUR,",5.406,MGRDLFAGEVPVLVLMVGNVDGANFAIAGVGFGDARRGLLVLLAVA...
2,7285095.0,1855588,"EGFP_4EUL,",5.24,MGRELFEGLRPVLVVMKGSVDGKNFALVGVGVGYPKLGLRAMVVVS...
3,6615822.0,1186315,"avGFP_2WUR,",5.17,MGRDLFSGPVPVLVLMLGSVDGARFAVLGVGVGYARLGFQAILAVF...
4,7258270.0,1828763,"EGFP_4EUL,",5.1,MGSSLFEGEVPVLVLALGDVDGRRFAVAGVGVGHRREGLLVAVLVA...

In [7]:
with open("../therm/output.fasta", "w") as f:
    for i, row in pre.head(10000).iterrows():
        f.write(">" + str(row[1]) + "\n")
        f.write(str(row[4]) + "\n")

In [8]:
!python3 ../therm/pptstab.py -i ../therm/output.fasta -o ../therm/output_SER.csv -f 1

############################################################################################
# This program PPTStab is developed for designing of thermostable proteins with a desired melting temperature #
# developed by Prof G. P. S. Raghava group.               #
# Please cite: PPTStab; available at https://webs.iiitd.edu.in/raghava/pptstab/  #
############################################################################################

======= Thanks for using Predict module of PPTStab. Your results will be stored in file : output_SER.csv  =====

Processing batches:   0%|                                | 0/79 [00:00<?, ?it/s]Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.
Processing batches: 100%|███████████████████████| 79/79 [04:03<00:00,  3.08s/it]
2026-07-01 10:36:23.123418857 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401375, index: 0, mask: {1, 49, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:36:23.124742546 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401379, index: 4, mask: {5, 53, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:36:23.132676615 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401380, index: 5, mask: {6, 54, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:36:23.136679454 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401381, index: 6, mask: {7, 55, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:36:23.140644672 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401382, index: 7, mask: {8, 56, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:36:23.144659507 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401383, index: 8, mask: {9, 57, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:36:23.151089728 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401384, index: 9, mask: {10, 58, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:36:23.154651170 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401385, index: 10, mask: {11, 59, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:36:23.159663428 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401386, index: 11, mask: {12, 60, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:36:23.159722212 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401387, index: 12, mask: {13, 61, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:36:23.159756236 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401388, index: 13, mask: {14, 62, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:36:23.159781388 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401389, index: 14, mask: {15, 63, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:36:23.159817060 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401390, index: 15, mask: {16, 64, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:36:23.159841524 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401391, index: 16, mask: {17, 65, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:36:23.159916716 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401392, index: 17, mask: {18, 66, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:36:23.159984527 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401393, index: 18, mask: {19, 67, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:36:23.159996638 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401395, index: 20, mask: {21, 69, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:36:23.160063917 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401396, index: 21, mask: {22, 70, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:36:23.160107630 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401397, index: 22, mask: {23, 71, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:36:23.160136701 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401398, index: 23, mask: {24, 72, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:36:23.160168128 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401399, index: 24, mask: {25, 73, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:36:23.160230262 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401400, index: 25, mask: {26, 74, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:36:23.163688060 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401401, index: 26, mask: {27, 75, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:36:23.167673975 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401402, index: 27, mask: {28, 76, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:36:23.171669619 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401403, index: 28, mask: {29, 77, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:36:23.175659307 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401404, index: 29, mask: {30, 78, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:36:23.179650184 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401405, index: 30, mask: {31, 79, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:36:23.183637887 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401413, index: 38, mask: {39, 87, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:36:23.187641072 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401414, index: 39, mask: {40, 88, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:36:23.191636243 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401415, index: 40, mask: {41, 89, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:36:23.192639303 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401394, index: 19, mask: {20, 68, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:36:23.196650758 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401416, index: 41, mask: {42, 90, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:36:23.240654248 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401412, index: 37, mask: {38, 86, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:36:23.240679036 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401411, index: 36, mask: {37, 85, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:36:23.244649225 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401410, index: 35, mask: {36, 84, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:36:23.248695200 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401421, index: 46, mask: {47, 95, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:36:23.260663887 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401409, index: 34, mask: {35, 83, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:36:23.264627636 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401406, index: 31, mask: {32, 80, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:36:23.268627729 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401408, index: 33, mask: {34, 82, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:36:23.272626819 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401407, index: 32, mask: {33, 81, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:36:23.276628345 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401418, index: 43, mask: {44, 92, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:36:23.280625461 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401419, index: 44, mask: {45, 93, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:36:23.284627257 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401420, index: 45, mask: {46, 94, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:36:23.304647869 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401417, index: 42, mask: {43, 91, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:36:23.319684293 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401376, index: 1, mask: {2, 50, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:36:23.323693441 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401377, index: 2, mask: {3, 51, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:36:23.327696812 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401378, index: 3, mask: {4, 52, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.

=========Process Completed. Have an awesome day ahead.=============

In [9]:
ppt_res = pd.read_csv('../therm/output_SER.csv')
ppt_res = ppt_res.rename(columns={'Tm(°C)' : 'SER'})
ppt_res

        seq_ID     SER                                           Sequence
0          >id  51.697                                            SEQENCE
1     >1379211  77.974  MGRDLFAGEVPVLVLMVGNVDGANFAIAGVGFGDARRGLLVLLAVA...
2     >1855588  66.449  MGRELFEGLRPVLVVMKGSVDGKNFALVGVGVGYPKLGLRAMVVVS...
3     >1186315  79.991  MGRDLFSGPVPVLVLMLGSVDGARFAVLGVGVGYARLGFQAILAVF...
4     >1828763  75.787  MGSSLFEGEVPVLVLALGDVDGRRFAVAGVGVGHRREGLLVAVLVA...
...        ...     ...                                                ...
9995   >104179  46.098  DAGRALLAGDVPLRVEAKGNVNGKEFEIVGEGVGNAQRGELRAVYT...
9996   >123312  54.889  AAGRALLAGPTPVRHRMRGDVNGKKFEVEGEGVGDAQTGRQRMTYT...
9997   >124303  48.480  SEGHALLAGPVPVEVHLKGNVNGREFEIRGEGVGDARTGRLSLLFT...
9998   >140046  46.693  SDGRALLADPTPVRTRMKGNVNGLEFEIEGEGVGDARTGRLEMTYV...
9999   >146150  47.444  SEGRKLLEGDVPLRVRLDGDVNGKRFRVEGEGVGNAQTGTQELRFV...

[10000 rows x 3 columns]

In [10]:
!python3 ../therm/pptstab.py -i ../therm/output.fasta -o ../therm/output_EMB.csv -f 0 -m EMB

############################################################################################
# This program PPTStab is developed for designing of thermostable proteins with a desired melting temperature #
# developed by Prof G. P. S. Raghava group.               #
# Please cite: PPTStab; available at https://webs.iiitd.edu.in/raghava/pptstab/  #
############################################################################################

======= Thanks for using Predict module of PPTStab. Your results will be stored in file : output_EMB.csv  =====

Processing batches:   0%|                                | 0/79 [00:00<?, ?it/s]Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.
Processing batches: 100%|███████████████████████| 79/79 [04:06<00:00,  3.12s/it]
2026-07-01 10:41:09.191153064 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401755, index: 0, mask: {1, 49, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:09.192458101 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401759, index: 4, mask: {5, 53, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:09.205668688 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401760, index: 5, mask: {6, 54, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:09.209680024 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401761, index: 6, mask: {7, 55, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:09.213664179 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401762, index: 7, mask: {8, 56, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:09.213730127 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401763, index: 8, mask: {9, 57, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:09.213767579 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401764, index: 9, mask: {10, 58, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:09.213799287 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401765, index: 10, mask: {11, 59, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:09.213833401 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401766, index: 11, mask: {12, 60, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:09.213906627 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401767, index: 12, mask: {13, 61, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:09.213955402 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401768, index: 13, mask: {14, 62, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:09.213989954 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401769, index: 14, mask: {15, 63, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:09.214020216 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401770, index: 15, mask: {16, 64, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:09.214079671 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401771, index: 16, mask: {17, 65, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:09.214122930 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401772, index: 17, mask: {18, 66, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:09.214157388 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401773, index: 18, mask: {19, 67, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:09.214192519 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401774, index: 19, mask: {20, 68, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:09.214254104 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401775, index: 20, mask: {21, 69, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:09.214287599 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401776, index: 21, mask: {22, 70, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:09.214317707 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401777, index: 22, mask: {23, 71, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:09.214348429 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401778, index: 23, mask: {24, 72, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:09.214376511 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401779, index: 24, mask: {25, 73, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:09.214438325 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401780, index: 25, mask: {26, 74, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:09.214468019 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401781, index: 26, mask: {27, 75, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:09.214500249 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401782, index: 27, mask: {28, 76, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:09.214533033 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401783, index: 28, mask: {29, 77, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:09.214594416 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401784, index: 29, mask: {30, 78, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:09.214632058 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401785, index: 30, mask: {31, 79, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:09.214668338 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401786, index: 31, mask: {32, 80, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:09.214698009 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401787, index: 32, mask: {33, 81, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:09.214733537 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401788, index: 33, mask: {34, 82, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:09.214816720 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401789, index: 34, mask: {35, 83, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:09.214850081 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401790, index: 35, mask: {36, 84, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:09.214882561 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401791, index: 36, mask: {37, 85, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:09.214914005 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401792, index: 37, mask: {38, 86, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:09.214973725 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401793, index: 38, mask: {39, 87, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:09.215017945 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401794, index: 39, mask: {40, 88, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:09.215047927 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401795, index: 40, mask: {41, 89, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:09.215087323 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401796, index: 41, mask: {42, 90, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:09.215221061 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401797, index: 42, mask: {43, 91, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:09.218667743 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401798, index: 43, mask: {44, 92, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:09.218734100 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401799, index: 44, mask: {45, 93, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:09.218791490 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401800, index: 45, mask: {46, 94, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:09.218823608 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401801, index: 46, mask: {47, 95, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:09.218893802 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401756, index: 1, mask: {2, 50, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:09.219089215 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401757, index: 2, mask: {3, 51, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:09.219279544 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401758, index: 3, mask: {4, 52, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.

=========Process Completed. Have an awesome day ahead.=============

In [11]:
ppt_emb = pd.read_csv('../therm/output_EMB.csv')
ppt_res['EMB'] = ppt_emb['Tm(°C)']
ppt_res

,seq_ID,SER,Sequence,EMB
0,>id,51.697,SEQENCE,56.287
1,>1379211,77.974,MGRDLFAGEVPVLVLMVGNVDGANFAIAGVGFGDARRGLLVLLAVA...,80.157
2,>1855588,66.449,MGRELFEGLRPVLVVMKGSVDGKNFALVGVGVGYPKLGLRAMVVVS...,71.119
3,>1186315,79.991,MGRDLFSGPVPVLVLMLGSVDGARFAVLGVGVGYARLGFQAILAVF...,80.665
4,>1828763,75.787,MGSSLFEGEVPVLVLALGDVDGRRFAVAGVGVGHRREGLLVAVLVA...,81.485
...,...,...,...,...
9995,>104179,46.098,DAGRALLAGDVPLRVEAKGNVNGKEFEIVGEGVGNAQRGELRAVYT...,54.542
9996,>123312,54.889,AAGRALLAGPTPVRHRMRGDVNGKKFEVEGEGVGDAQTGRQRMTYT...,63.491
9997,>124303,48.480,SEGHALLAGPVPVEVHLKGNVNGREFEIRGEGVGDARTGRLSLLFT...,54.602
9998,>140046,46.693,SDGRALLADPTPVRTRMKGNVNGLEFEIEGEGVGDARTGRLEMTYV...,54.438
9999,>146150,47.444,SEGRKLLEGDVPLRVRLDGDVNGKRFRVEGEGVGNAQTGTQELRFV...,55.583

In [12]:
!python3 ../therm/pptstab.py -i ../therm/output.fasta -o ../therm/output_AAC.csv -f 0 -m AAC -d2

############################################################################################
# This program PPTStab is developed for designing of thermostable proteins with a desired melting temperature #
# developed by Prof G. P. S. Raghava group.               #
# Please cite: PPTStab; available at https://webs.iiitd.edu.in/raghava/pptstab/  #
############################################################################################

======= Thanks for using Predict module of PPTStab. Your results will be stored in file : output_AAC.csv  =====

2026-07-01 10:41:52.290119697 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401872, index: 0, mask: {1, 49, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:52.291348992 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401876, index: 4, mask: {5, 53, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:52.298664517 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401877, index: 5, mask: {6, 54, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:52.302655776 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401878, index: 6, mask: {7, 55, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:52.302740257 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401879, index: 7, mask: {8, 56, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:52.302768070 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401880, index: 8, mask: {9, 57, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:52.302795144 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401881, index: 9, mask: {10, 58, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:52.302822523 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401882, index: 10, mask: {11, 59, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:52.302902796 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401883, index: 11, mask: {12, 60, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:52.302928636 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401884, index: 12, mask: {13, 61, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:52.302956721 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401885, index: 13, mask: {14, 62, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:52.302983820 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401886, index: 14, mask: {15, 63, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:52.303010028 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401887, index: 15, mask: {16, 64, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:52.303033908 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401888, index: 16, mask: {17, 65, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:52.306644131 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401889, index: 17, mask: {18, 66, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:52.306682808 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401890, index: 18, mask: {19, 67, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:52.306714567 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401891, index: 19, mask: {20, 68, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:52.306739665 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401892, index: 20, mask: {21, 69, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:52.306770337 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401893, index: 21, mask: {22, 70, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:52.306795202 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401894, index: 22, mask: {23, 71, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:52.306851835 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401895, index: 23, mask: {24, 72, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:52.306877982 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401896, index: 24, mask: {25, 73, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:52.306907914 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401897, index: 25, mask: {26, 74, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:52.306931832 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401898, index: 26, mask: {27, 75, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:52.306958818 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401899, index: 27, mask: {28, 76, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:52.306981858 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401900, index: 28, mask: {29, 77, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:52.307044789 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401901, index: 29, mask: {30, 78, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:52.307068999 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401902, index: 30, mask: {31, 79, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:52.307096363 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401903, index: 31, mask: {32, 80, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:52.307121340 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401904, index: 32, mask: {33, 81, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:52.307149957 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401905, index: 33, mask: {34, 82, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:52.307174033 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401906, index: 34, mask: {35, 83, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:52.307241554 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401907, index: 35, mask: {36, 84, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:52.307265507 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401908, index: 36, mask: {37, 85, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:52.307297069 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401909, index: 37, mask: {38, 86, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:52.307322341 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401910, index: 38, mask: {39, 87, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:52.307349793 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401911, index: 39, mask: {40, 88, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:52.307424781 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401912, index: 40, mask: {41, 89, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:52.307451739 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401913, index: 41, mask: {42, 90, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:52.307476471 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401914, index: 42, mask: {43, 91, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:52.307504379 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401915, index: 43, mask: {44, 92, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:52.307531012 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401916, index: 44, mask: {45, 93, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:52.307584743 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401917, index: 45, mask: {46, 94, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:52.307610342 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401918, index: 46, mask: {47, 95, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:52.307945259 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401873, index: 1, mask: {2, 50, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:52.315452914 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401875, index: 3, mask: {4, 52, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:41:52.313663178 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1401874, index: 2, mask: {3, 51, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.

=========Process Completed. Have an awesome day ahead.=============

In [13]:
ppt_aac = pd.read_csv('../therm/output_AAC.csv')
ppt_res['AAC'] = ppt_emb['Tm(°C)']
ppt_res

,seq_ID,SER,Sequence,EMB,AAC
0,>id,51.697,SEQENCE,56.287,56.287
1,>1379211,77.974,MGRDLFAGEVPVLVLMVGNVDGANFAIAGVGFGDARRGLLVLLAVA...,80.157,80.157
2,>1855588,66.449,MGRELFEGLRPVLVVMKGSVDGKNFALVGVGVGYPKLGLRAMVVVS...,71.119,71.119
3,>1186315,79.991,MGRDLFSGPVPVLVLMLGSVDGARFAVLGVGVGYARLGFQAILAVF...,80.665,80.665
4,>1828763,75.787,MGSSLFEGEVPVLVLALGDVDGRRFAVAGVGVGHRREGLLVAVLVA...,81.485,81.485
...,...,...,...,...,...
9995,>104179,46.098,DAGRALLAGDVPLRVEAKGNVNGKEFEIVGEGVGNAQRGELRAVYT...,54.542,54.542
9996,>123312,54.889,AAGRALLAGPTPVRHRMRGDVNGKKFEVEGEGVGDAQTGRQRMTYT...,63.491,63.491
9997,>124303,48.480,SEGHALLAGPVPVEVHLKGNVNGREFEIRGEGVGDARTGRLSLLFT...,54.602,54.602
9998,>140046,46.693,SDGRALLADPTPVRTRMKGNVNGLEFEIEGEGVGDARTGRLEMTYV...,54.438,54.438
9999,>146150,47.444,SEGRKLLEGDVPLRVRLDGDVNGKRFRVEGEGVGNAQTGTQELRFV...,55.583,55.583

In [14]:
!python3 ../therm/pptstab.py -i ../therm/output.fasta -o ../therm/output_EMB2.csv -f 1 -m EMB

############################################################################################
# This program PPTStab is developed for designing of thermostable proteins with a desired melting temperature #
# developed by Prof G. P. S. Raghava group.               #
# Please cite: PPTStab; available at https://webs.iiitd.edu.in/raghava/pptstab/  #
############################################################################################

======= Thanks for using Predict module of PPTStab. Your results will be stored in file : output_EMB2.csv  =====

Processing batches:   0%|                                | 0/79 [00:00<?, ?it/s]Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.
Processing batches: 100%|███████████████████████| 79/79 [04:05<00:00,  3.11s/it]
2026-07-01 10:50:09.824507479 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1402484, index: 0, mask: {1, 49, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:50:09.825852079 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1402488, index: 4, mask: {5, 53, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:50:09.833670433 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1402489, index: 5, mask: {6, 54, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:50:09.841675862 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1402490, index: 6, mask: {7, 55, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:50:09.845646178 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1402491, index: 7, mask: {8, 56, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:50:09.849666625 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1402492, index: 8, mask: {9, 57, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:50:09.858657782 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1402494, index: 10, mask: {11, 59, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:50:09.858692721 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1402495, index: 11, mask: {12, 60, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:50:09.858716258 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1402496, index: 12, mask: {13, 61, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:50:09.858737082 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1402497, index: 13, mask: {14, 62, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:50:09.858758183 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1402498, index: 14, mask: {15, 63, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:50:09.858778969 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1402499, index: 15, mask: {16, 64, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:50:09.858803480 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1402500, index: 16, mask: {17, 65, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:50:09.858828066 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1402501, index: 17, mask: {18, 66, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:50:09.858851498 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1402502, index: 18, mask: {19, 67, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:50:09.858878986 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1402503, index: 19, mask: {20, 68, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:50:09.858899872 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1402504, index: 20, mask: {21, 69, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:50:09.858921151 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1402505, index: 21, mask: {22, 70, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:50:09.858941090 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1402506, index: 22, mask: {23, 71, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:50:09.858963621 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1402507, index: 23, mask: {24, 72, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:50:09.858986209 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1402508, index: 24, mask: {25, 73, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:50:09.859008379 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1402509, index: 25, mask: {26, 74, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:50:09.859035246 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1402510, index: 26, mask: {27, 75, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:50:09.859058011 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1402511, index: 27, mask: {28, 76, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:50:09.859077971 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1402512, index: 28, mask: {29, 77, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:50:09.859099331 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1402513, index: 29, mask: {30, 78, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:50:09.859124207 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1402514, index: 30, mask: {31, 79, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:50:09.859148341 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1402515, index: 31, mask: {32, 80, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:50:09.859173639 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1402516, index: 32, mask: {33, 81, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:50:09.859195138 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1402517, index: 33, mask: {34, 82, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:50:09.859222644 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1402518, index: 34, mask: {35, 83, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:50:09.859244046 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1402519, index: 35, mask: {36, 84, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:50:09.859265461 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1402520, index: 36, mask: {37, 85, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:50:09.859286364 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1402521, index: 37, mask: {38, 86, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:50:09.859308872 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1402522, index: 38, mask: {39, 87, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:50:09.859330493 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1402523, index: 39, mask: {40, 88, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:50:09.859352073 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1402524, index: 40, mask: {41, 89, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:50:09.859378447 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1402525, index: 41, mask: {42, 90, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:50:09.859401126 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1402526, index: 42, mask: {43, 91, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:50:09.859420947 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1402527, index: 43, mask: {44, 92, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:50:09.859441586 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1402528, index: 44, mask: {45, 93, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:50:09.859462788 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1402529, index: 45, mask: {46, 94, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:50:09.859484890 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1402530, index: 46, mask: {47, 95, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:50:09.859509705 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1402485, index: 1, mask: {2, 50, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:50:09.866706015 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1402487, index: 3, mask: {4, 52, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:50:09.866753555 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1402486, index: 2, mask: {3, 51, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2026-07-01 10:50:09.928626917 [E:onnxruntime:Default, env.cc:228 ThreadMain] pthread_setaffinity_np failed for thread: 1402493, index: 9, mask: {10, 58, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.

=========Process Completed. Have an awesome day ahead.=============

In [15]:
ppt_emb = pd.read_csv('../therm/output_EMB2.csv')
ppt_res['EMB2'] = ppt_emb['Tm(°C)']
ppt_res

,seq_ID,SER,Sequence,EMB,AAC,EMB2
0,>id,51.697,SEQENCE,56.287,56.287,51.697
1,>1379211,77.974,MGRDLFAGEVPVLVLMVGNVDGANFAIAGVGFGDARRGLLVLLAVA...,80.157,80.157,77.974
2,>1855588,66.449,MGRELFEGLRPVLVVMKGSVDGKNFALVGVGVGYPKLGLRAMVVVS...,71.119,71.119,66.449
3,>1186315,79.991,MGRDLFSGPVPVLVLMLGSVDGARFAVLGVGVGYARLGFQAILAVF...,80.665,80.665,79.991
4,>1828763,75.787,MGSSLFEGEVPVLVLALGDVDGRRFAVAGVGVGHRREGLLVAVLVA...,81.485,81.485,75.787
...,...,...,...,...,...,...
9995,>104179,46.098,DAGRALLAGDVPLRVEAKGNVNGKEFEIVGEGVGNAQRGELRAVYT...,54.542,54.542,46.098
9996,>123312,54.889,AAGRALLAGPTPVRHRMRGDVNGKKFEVEGEGVGDAQTGRQRMTYT...,63.491,63.491,54.889
9997,>124303,48.480,SEGHALLAGPVPVEVHLKGNVNGREFEIRGEGVGDARTGRLSLLFT...,54.602,54.602,48.480
9998,>140046,46.693,SDGRALLADPTPVRTRMKGNVNGLEFEIEGEGVGDARTGRLEMTYV...,54.438,54.438,46.693
9999,>146150,47.444,SEGRKLLEGDVPLRVRLDGDVNGKRFRVEGEGVGNAQTGTQELRFV...,55.583,55.583,47.444

In [16]:
ppt_res = ppt_res.rename(columns={'EMB' : 'EMB2', 'EMB2' : 'EMB'})
ppt_res

,seq_ID,SER,Sequence,EMB2,AAC,EMB
0,>id,51.697,SEQENCE,56.287,56.287,51.697
1,>1379211,77.974,MGRDLFAGEVPVLVLMVGNVDGANFAIAGVGFGDARRGLLVLLAVA...,80.157,80.157,77.974
2,>1855588,66.449,MGRELFEGLRPVLVVMKGSVDGKNFALVGVGVGYPKLGLRAMVVVS...,71.119,71.119,66.449
3,>1186315,79.991,MGRDLFSGPVPVLVLMLGSVDGARFAVLGVGVGYARLGFQAILAVF...,80.665,80.665,79.991
4,>1828763,75.787,MGSSLFEGEVPVLVLALGDVDGRRFAVAGVGVGHRREGLLVAVLVA...,81.485,81.485,75.787
...,...,...,...,...,...,...
9995,>104179,46.098,DAGRALLAGDVPLRVEAKGNVNGKEFEIVGEGVGNAQRGELRAVYT...,54.542,54.542,46.098
9996,>123312,54.889,AAGRALLAGPTPVRHRMRGDVNGKKFEVEGEGVGDAQTGRQRMTYT...,63.491,63.491,54.889
9997,>124303,48.480,SEGHALLAGPVPVEVHLKGNVNGREFEIRGEGVGDARTGRLSLLFT...,54.602,54.602,48.480
9998,>140046,46.693,SDGRALLADPTPVRTRMKGNVNGLEFEIEGEGVGDARTGRLEMTYV...,54.438,54.438,46.693
9999,>146150,47.444,SEGRKLLEGDVPLRVRLDGDVNGKRFRVEGEGVGNAQTGTQELRFV...,55.583,55.583,47.444

In [17]:
labels = pd.read_csv('../therm/labels.csv')
labels = labels.rename({'Functional Thermostability (C)': 'func_therm'}, axis = 1)

In [18]:
labels["clas"] = (labels["func_therm"] > 72).astype(int)

In [19]:
ppt_res['seq_len'] = ppt_res['Sequence'].apply(len)

In [20]:
import Bio
from Bio.SeqUtils.ProtParam import ProteinAnalysis
import torch
DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'
DEVICE

'cuda'

In [21]:
data = ppt_res
data

,seq_ID,SER,Sequence,EMB2,AAC,EMB,seq_len
0,>id,51.697,SEQENCE,56.287,56.287,51.697,7
1,>1379211,77.974,MGRDLFAGEVPVLVLMVGNVDGANFAIAGVGFGDARRGLLVLLAVA...,80.157,80.157,77.974,226
2,>1855588,66.449,MGRELFEGLRPVLVVMKGSVDGKNFALVGVGVGYPKLGLRAMVVVS...,71.119,71.119,66.449,226
3,>1186315,79.991,MGRDLFSGPVPVLVLMLGSVDGARFAVLGVGVGYARLGFQAILAVF...,80.665,80.665,79.991,226
4,>1828763,75.787,MGSSLFEGEVPVLVLALGDVDGRRFAVAGVGVGHRREGLLVAVLVA...,81.485,81.485,75.787,226
...,...,...,...,...,...,...,...
9995,>104179,46.098,DAGRALLAGDVPLRVEAKGNVNGKEFEIVGEGVGNAQRGELRAVYT...,54.542,54.542,46.098,342
9996,>123312,54.889,AAGRALLAGPTPVRHRMRGDVNGKKFEVEGEGVGDAQTGRQRMTYT...,63.491,63.491,54.889,342
9997,>124303,48.480,SEGHALLAGPVPVEVHLKGNVNGREFEIRGEGVGDARTGRLSLLFT...,54.602,54.602,48.480,342
9998,>140046,46.693,SDGRALLADPTPVRTRMKGNVNGLEFEIEGEGVGDARTGRLEMTYV...,54.438,54.438,46.693,342
9999,>146150,47.444,SEGRKLLEGDVPLRVRLDGDVNGKRFRVEGEGVGNAQTGTQELRFV...,55.583,55.583,47.444,342

In [25]:
def extract_descriptors(Sequence):
    analyzed_seq = ProteinAnalysis(Sequence)


    descriptors = {
        'molecular_weight': analyzed_seq.molecular_weight(),
        'aromaticity': analyzed_seq.aromaticity(),
        'instability_index': analyzed_seq.instability_index(),
        'isoelectric_point': analyzed_seq.isoelectric_point(),
        'gravy': analyzed_seq.gravy(),
        'charge_at_pH7': analyzed_seq.charge_at_pH(pH=7),
        'ss_a-helix': analyzed_seq.secondary_structure_fraction()[0],
        'ss_turn': analyzed_seq.secondary_structure_fraction()[1],
        'ss_b-sheet': analyzed_seq.secondary_structure_fraction()[2]
    }


    aa_composition = analyzed_seq.amino_acids_percent
    for aa, value in aa_composition.items():
        descriptors[f'aa_{aa}'] = value

    return descriptors

data['descriptors'] = data['Sequence'].apply(extract_descriptors)
descriptors_df = data['descriptors'].apply(pd.Series)
data = pd.concat([data, descriptors_df], axis=1)
data.head()

,seq_ID,SER,Sequence,EMB2,AAC,EMB,seq_len,descriptors,molecular_weight,aromaticity,...,aa_M,aa_N,aa_P,aa_Q,aa_R,aa_S,aa_T,aa_V,aa_W,aa_Y
0,>id,51.697,SEQENCE,56.287,56.287,51.697,7,"{'molecular_weight': 837.8092999999998, 'aroma...",837.8093,0.000000,...,0.000000,14.285714,0.000000,14.285714,0.000000,14.285714,0.000000,0.000000,0.000000,0.000000
1,>1379211,77.974,MGRDLFAGEVPVLVLMVGNVDGANFAIAGVGFGDARRGLLVLLAVA...,80.157,80.157,77.974,226,"{'molecular_weight': 24871.578200000014, 'arom...",24871.5782,0.106195,...,1.769912,2.212389,7.522124,1.327434,6.637168,3.539823,3.539823,11.061947,0.884956,6.637168
2,>1855588,66.449,MGRELFEGLRPVLVVMKGSVDGKNFALVGVGVGYPKLGLRAMVVVS...,71.119,71.119,66.449,226,"{'molecular_weight': 24815.606400000026, 'arom...",24815.6064,0.097345,...,2.654867,3.097345,8.407080,0.442478,5.752212,3.982301,3.539823,11.946903,0.884956,4.867257
3,>1186315,79.991,MGRDLFSGPVPVLVLMLGSVDGARFAVLGVGVGYARLGFQAILAVF...,80.665,80.665,79.991,226,"{'molecular_weight': 24698.303000000014, 'arom...",24698.3030,0.097345,...,1.769912,0.884956,7.964602,0.884956,7.522124,3.982301,3.982301,11.061947,0.442478,5.752212
4,>1828763,75.787,MGSSLFEGEVPVLVLALGDVDGRRFAVAGVGVGHRREGLLVAVLVA...,81.485,81.485,75.787,226,"{'molecular_weight': 24398.003500000003, 'arom...",24398.0035,0.092920,...,1.327434,2.212389,7.964602,0.442478,7.079646,4.867257,2.654867,12.831858,0.884956,4.424779

In [26]:
data = data.iloc[1:].reset_index(drop=True)

In [27]:
data

,seq_ID,SER,Sequence,EMB2,AAC,EMB,seq_len,descriptors,molecular_weight,aromaticity,...,aa_M,aa_N,aa_P,aa_Q,aa_R,aa_S,aa_T,aa_V,aa_W,aa_Y
0,>1379211,77.974,MGRDLFAGEVPVLVLMVGNVDGANFAIAGVGFGDARRGLLVLLAVA...,80.157,80.157,77.974,226,"{'molecular_weight': 24871.578200000014, 'arom...",24871.5782,0.106195,...,1.769912,2.212389,7.522124,1.327434,6.637168,3.539823,3.539823,11.061947,0.884956,6.637168
1,>1855588,66.449,MGRELFEGLRPVLVVMKGSVDGKNFALVGVGVGYPKLGLRAMVVVS...,71.119,71.119,66.449,226,"{'molecular_weight': 24815.606400000026, 'arom...",24815.6064,0.097345,...,2.654867,3.097345,8.407080,0.442478,5.752212,3.982301,3.539823,11.946903,0.884956,4.867257
2,>1186315,79.991,MGRDLFSGPVPVLVLMLGSVDGARFAVLGVGVGYARLGFQAILAVF...,80.665,80.665,79.991,226,"{'molecular_weight': 24698.303000000014, 'arom...",24698.3030,0.097345,...,1.769912,0.884956,7.964602,0.884956,7.522124,3.982301,3.982301,11.061947,0.442478,5.752212
3,>1828763,75.787,MGSSLFEGEVPVLVLALGDVDGRRFAVAGVGVGHRREGLLVAVLVA...,81.485,81.485,75.787,226,"{'molecular_weight': 24398.003500000003, 'arom...",24398.0035,0.092920,...,1.327434,2.212389,7.964602,0.442478,7.079646,4.867257,2.654867,12.831858,0.884956,4.424779
4,>1283538,78.792,MGADLLSGPVPVLVALLGDADGARFAVLGAGVGFARRGLLVLLAVN...,80.615,80.615,78.792,226,"{'molecular_weight': 24173.85320000001, 'aroma...",24173.8532,0.084071,...,0.884956,1.327434,9.734513,0.000000,7.522124,3.982301,1.769912,12.389381,0.442478,5.309735
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9994,>104179,46.098,DAGRALLAGDVPLRVEAKGNVNGKEFEIVGEGVGNAQRGELRAVYT...,54.542,54.542,46.098,342,"{'molecular_weight': 37383.49990000007, 'aroma...",37383.4999,0.067251,...,1.169591,3.801170,6.140351,3.216374,6.432749,6.432749,6.725146,9.356725,1.461988,1.754386
9995,>123312,54.889,AAGRALLAGPTPVRHRMRGDVNGKKFEVEGEGVGDAQTGRQRMTYT...,63.491,63.491,54.889,342,"{'molecular_weight': 37418.811000000045, 'arom...",37418.8110,0.067251,...,1.461988,1.169591,6.725146,2.923977,7.894737,4.970760,7.602339,10.818713,0.877193,2.046784
9996,>124303,48.480,SEGHALLAGPVPVEVHLKGNVNGREFEIRGEGVGDARTGRLSLLFT...,54.602,54.602,48.480,342,"{'molecular_weight': 37512.73510000006, 'aroma...",37512.7351,0.067251,...,1.461988,2.631579,7.017544,1.461988,6.140351,7.309942,8.187135,9.649123,1.461988,2.631579
9997,>140046,46.693,SDGRALLADPTPVRTRMKGNVNGLEFEIEGEGVGDARTGRLEMTYV...,54.438,54.438,46.693,342,"{'molecular_weight': 37703.86570000007, 'aroma...",37703.8657,0.070175,...,1.754386,3.216374,5.555556,2.339181,6.432749,6.140351,9.064327,8.771930,1.169591,2.339181
9998,>146150,47.444,SEGRKLLEGDVPLRVRLDGDVNGKRFRVEGEGVGNAQTGTQELRFV...,55.583,55.583,47.444,342,"{'molecular_weight': 37511.58190000008, 'aroma...",37511.5819,0.055556,...,0.584795,2.046784,5.847953,3.508772,7.602339,5.847953,8.479532,10.526316,1.169591,1.754386

In [28]:
data = data.drop('descriptors', axis=1)

In [29]:

from transformers import AutoTokenizer, EsmModel
from tqdm import tqdm



tokenizer = AutoTokenizer.from_pretrained("facebook/esm2_t33_650M_UR50D")
model = EsmModel.from_pretrained("facebook/esm2_t33_650M_UR50D").to(DEVICE)
model.eval()

embeddings = []

for seq in tqdm(data["Sequence"]):
    inputs = tokenizer(seq, return_tensors="pt", truncation=True).to(DEVICE)

    with torch.no_grad():
        outputs = model(**inputs)

    emb = outputs.last_hidden_state[:, 1:-1].mean(dim=1).squeeze().cpu().numpy()
    embeddings.append(emb)

/trinity/home/p_oleinikov/.conda/envs/ppstab2/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Some weights of EsmModel were not initialized from the model checkpoint at facebook/esm2_t33_650M_UR50D and are newly initialized: ['esm.pooler.dense.bias', 'esm.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
  0%|          | 0/9999 [00:00<?, ?it/s]Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.
100%|██████████| 9999/9999 [07:14<00:00, 23.02it/s]

In [30]:
X = pd.DataFrame(
    embeddings,
    columns=[f"emb_{i}" for i in range(len(embeddings[0]))]
)
data = pd.concat([data, X], axis=1)

In [31]:
data

,seq_ID,SER,Sequence,EMB2,AAC,EMB,seq_len,molecular_weight,aromaticity,instability_index,...,emb_1270,emb_1271,emb_1272,emb_1273,emb_1274,emb_1275,emb_1276,emb_1277,emb_1278,emb_1279
0,>1379211,77.974,MGRDLFAGEVPVLVLMVGNVDGANFAIAGVGFGDARRGLLVLLAVA...,80.157,80.157,77.974,226,24871.5782,0.106195,32.226106,...,0.109929,0.073005,0.008115,0.122912,-0.006657,0.111748,0.052604,-0.048403,0.067519,-0.084471
1,>1855588,66.449,MGRELFEGLRPVLVVMKGSVDGKNFALVGVGVGYPKLGLRAMVVVS...,71.119,71.119,66.449,226,24815.6064,0.097345,27.871239,...,0.146607,0.072872,-0.037738,0.250836,-0.018934,0.043748,0.107054,-0.144702,0.063847,-0.135173
2,>1186315,79.991,MGRDLFSGPVPVLVLMLGSVDGARFAVLGVGVGYARLGFQAILAVF...,80.665,80.665,79.991,226,24698.3030,0.097345,50.903097,...,-0.043685,0.027612,-0.064697,0.138363,0.013731,0.021259,-0.000714,-0.005943,-0.009956,-0.050849
3,>1828763,75.787,MGSSLFEGEVPVLVLALGDVDGRRFAVAGVGVGHRREGLLVAVLVA...,81.485,81.485,75.787,226,24398.0035,0.092920,31.591593,...,0.053924,0.074759,-0.058464,0.146572,0.012798,0.041014,0.039836,-0.031868,0.053415,-0.015060
4,>1283538,78.792,MGADLLSGPVPVLVALLGDADGARFAVLGAGVGFARRGLLVLLAVN...,80.615,80.615,78.792,226,24173.8532,0.084071,31.789381,...,0.014999,0.042315,-0.034835,0.099143,0.018207,0.066471,0.042846,-0.021110,0.029446,-0.062992
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9994,>104179,46.098,DAGRALLAGDVPLRVEAKGNVNGKEFEIVGEGVGNAQRGELRAVYT...,54.542,54.542,46.098,342,37383.4999,0.067251,28.543012,...,0.078056,0.038029,-0.040128,0.007463,0.001547,-0.056949,0.073136,0.001345,-0.038258,0.050697
9995,>123312,54.889,AAGRALLAGPTPVRHRMRGDVNGKKFEVEGEGVGDAQTGRQRMTYT...,63.491,63.491,54.889,342,37418.8110,0.067251,35.971053,...,0.043406,0.004319,-0.047475,0.010665,-0.016419,-0.038964,0.096877,-0.016057,-0.033251,0.048270
9996,>124303,48.480,SEGHALLAGPVPVEVHLKGNVNGREFEIRGEGVGDARTGRLSLLFT...,54.602,54.602,48.480,342,37512.7351,0.067251,37.542105,...,0.090486,0.046885,-0.081142,0.003365,-0.015695,-0.056584,0.078088,-0.015728,-0.004072,0.011623
9997,>140046,46.693,SDGRALLADPTPVRTRMKGNVNGLEFEIEGEGVGDARTGRLEMTYV...,54.438,54.438,46.693,342,37703.8657,0.070175,38.214912,...,0.086514,0.028280,-0.017121,0.001272,-0.020815,-0.033356,0.100702,-0.002994,-0.050231,0.039036
9998,>146150,47.444,SEGRKLLEGDVPLRVRLDGDVNGKRFRVEGEGVGNAQTGTQELRFV...,55.583,55.583,47.444,342,37511.5819,0.055556,34.643860,...,0.068985,0.030060,-0.081049,0.015295,-0.012021,-0.050009,0.073071,0.007069,-0.005548,0.043196

In [32]:
data_train = pd.read_csv('../therm/train.csv')
data_train

,Unnamed: 0,seq_ID,SER,Sequence,EMB2,AAC,EMB,seq_len,molecular_weight,aromaticity,...,emb_1270,emb_1271,emb_1272,emb_1273,emb_1274,emb_1275,emb_1276,emb_1277,emb_1278,emb_1279
0,0,>fast.2,48.647,MGSSHHHHHHVSKGEELFTGVVPILVELDGDVNGHKFSVRGEGEGD...,49.841,49.841,48.647,248,28297.6153,0.100806,...,0.190409,0.041503,0.045698,0.103734,-0.031538,0.116492,0.064738,-0.048019,0.023995,-0.036210
1,1,>slow.3,48.845,MGSSHHHHHHVSKGEELFTGVVPILVELDGDVNGHKFSVRGEGEGD...,49.912,49.912,48.845,248,28224.4984,0.100806,...,0.185395,0.031151,0.040534,0.097895,-0.026833,0.125951,0.064972,-0.037655,0.035778,-0.042235
2,2,>fast.3,48.932,MGSSHHHHHHVSKGEELFTGVVPILVELDGDVNGHKFSVRGEGEGD...,49.741,49.741,48.932,248,28182.4419,0.100806,...,0.182074,0.026957,0.043923,0.107127,-0.026680,0.122869,0.047613,-0.047101,0.039740,-0.049248
3,3,>bleach.2,48.378,MGSSHHHHHHVSKGEELFTGVVPILVELDGDVNGHKFSVRGEGEGD...,49.766,49.766,48.378,248,28243.4820,0.100806,...,0.173794,0.027828,0.037849,0.104220,-0.024550,0.120089,0.045973,-0.036622,0.033518,-0.051738
4,4,>bleach.6,49.035,MGSSHHHHHHVSKGEELFTGVVPILVELDGDVNGHKFSVRGEGEGD...,49.764,49.764,49.035,248,28293.6450,0.100806,...,0.176285,0.031075,0.039704,0.096253,-0.020991,0.113704,0.055306,-0.034333,0.020264,-0.039954
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,67,>sf:mid.12,49.791,MGSSHHHHHHVSKGEELFTGVVPILVELDGDVNGHKFSVRGEGEGD...,49.945,49.945,49.791,249,27967.2756,0.084337,...,0.180051,0.042190,0.024648,0.108867,-0.024328,0.086961,0.060614,-0.014354,-0.011579,-0.025871
68,68,>sf:mid.5,49.794,MGSSHHHHHHVSKGEELFTGVVPILVELDGDVNGHKFSVRGEGEGD...,49.784,49.784,49.794,249,28005.2375,0.088353,...,0.178148,0.044811,0.021309,0.107309,-0.023493,0.088570,0.063058,-0.021769,-0.013064,-0.025362
69,69,>sf:thermo.9,50.077,MGSSHHHHHHVSKGEELFTGVVPILVELDGDVNGHKFSVRGEGEGD...,49.700,49.700,50.077,249,28046.2314,0.088353,...,0.172857,0.042234,0.022921,0.122957,-0.025753,0.098913,0.062129,-0.018722,-0.002649,-0.038387
70,70,>sf:mid.7,49.806,MGSSHHHHHHVSKGEELFTGVVPILVELDGDVNGHKFSVRGEGEGD...,49.807,49.807,49.806,249,28025.2075,0.088353,...,0.180369,0.040567,0.026506,0.116053,-0.028530,0.104105,0.058014,-0.014005,0.001443,-0.037387
71,71,>sf:mid.10,49.904,MGSSHHHHHHVSKGEELFTGVVPILVELDGDVNGHKFSVRGEGEGD...,49.744,49.744,49.904,249,27964.2104,0.088353,...,0.180649,0.045034,0.023930,0.116004,-0.029918,0.100914,0.056566,-0.015034,-0.008189,-0.030946

In [33]:
x = data_train.drop(['seq_ID', 'Sequence', 'Unnamed: 0'], axis = 1)
x

,SER,EMB2,AAC,EMB,seq_len,molecular_weight,aromaticity,instability_index,isoelectric_point,gravy,...,emb_1270,emb_1271,emb_1272,emb_1273,emb_1274,emb_1275,emb_1276,emb_1277,emb_1278,emb_1279
0,48.647,49.841,49.841,48.647,248,28297.6153,0.100806,31.805242,5.822098,-0.522984,...,0.190409,0.041503,0.045698,0.103734,-0.031538,0.116492,0.064738,-0.048019,0.023995,-0.036210
1,48.845,49.912,49.912,48.845,248,28224.4984,0.100806,31.254839,5.822098,-0.505645,...,0.185395,0.031151,0.040534,0.097895,-0.026833,0.125951,0.064972,-0.037655,0.035778,-0.042235
2,48.932,49.741,49.741,48.932,248,28182.4419,0.100806,32.069758,5.822098,-0.536290,...,0.182074,0.026957,0.043923,0.107127,-0.026680,0.122869,0.047613,-0.047101,0.039740,-0.049248
3,48.378,49.766,49.766,48.378,248,28243.4820,0.100806,30.071774,5.822098,-0.566935,...,0.173794,0.027828,0.037849,0.104220,-0.024550,0.120089,0.045973,-0.036622,0.033518,-0.051738
4,49.035,49.764,49.764,49.035,248,28293.6450,0.100806,29.863710,5.770204,-0.525806,...,0.176285,0.031075,0.039704,0.096253,-0.020991,0.113704,0.055306,-0.034333,0.020264,-0.039954
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,49.791,49.945,49.945,49.791,249,27967.2756,0.084337,22.424096,6.147103,-0.495984,...,0.180051,0.042190,0.024648,0.108867,-0.024328,0.086961,0.060614,-0.014354,-0.011579,-0.025871
68,49.794,49.784,49.784,49.794,249,28005.2375,0.088353,23.693173,6.147103,-0.537349,...,0.178148,0.044811,0.021309,0.107309,-0.023493,0.088570,0.063058,-0.021769,-0.013064,-0.025362
69,50.077,49.700,49.700,50.077,249,28046.2314,0.088353,26.612450,6.334956,-0.570683,...,0.172857,0.042234,0.022921,0.122957,-0.025753,0.098913,0.062129,-0.018722,-0.002649,-0.038387
70,49.806,49.807,49.807,49.806,249,28025.2075,0.088353,23.926104,6.189732,-0.562249,...,0.180369,0.040567,0.026506,0.116053,-0.028530,0.104105,0.058014,-0.014005,0.001443,-0.037387
71,49.904,49.744,49.744,49.904,249,27964.2104,0.088353,23.546988,6.189732,-0.498795,...,0.180649,0.045034,0.023930,0.116004,-0.029918,0.100914,0.056566,-0.015034,-0.008189,-0.030946

In [34]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, labels.clas, test_size = 0.25, stratify = labels.clas)
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(54, 1314) (18, 1314) (54,) (18,)

In [37]:
from sklearn.ensemble import GradientBoostingClassifier
model_cl_grad = GradientBoostingClassifier(n_estimators=150)
model_cl_grad.fit(x_train, y_train)
y_pred_grad = model_cl_grad.predict(x_test)
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred_grad))

              precision    recall  f1-score   support

           0       0.62      0.62      0.62         8
           1       0.70      0.70      0.70        10

    accuracy                           0.67        18
   macro avg       0.66      0.66      0.66        18
weighted avg       0.67      0.67      0.67        18

In [41]:
from sklearn.ensemble import ExtraTreesClassifier
model_cl_extra = ExtraTreesClassifier(n_estimators=1500)
model_cl_extra.fit(x_train, y_train)
y_pred_extra = model_cl_extra.predict(x_test)

print(classification_report(y_test, y_pred_extra))

              precision    recall  f1-score   support

           0       0.71      0.62      0.67         8
           1       0.73      0.80      0.76        10

    accuracy                           0.72        18
   macro avg       0.72      0.71      0.71        18
weighted avg       0.72      0.72      0.72        18

In [42]:
data

,seq_ID,SER,Sequence,EMB2,AAC,EMB,seq_len,molecular_weight,aromaticity,instability_index,...,emb_1270,emb_1271,emb_1272,emb_1273,emb_1274,emb_1275,emb_1276,emb_1277,emb_1278,emb_1279
0,>1379211,77.974,MGRDLFAGEVPVLVLMVGNVDGANFAIAGVGFGDARRGLLVLLAVA...,80.157,80.157,77.974,226,24871.5782,0.106195,32.226106,...,0.109929,0.073005,0.008115,0.122912,-0.006657,0.111748,0.052604,-0.048403,0.067519,-0.084471
1,>1855588,66.449,MGRELFEGLRPVLVVMKGSVDGKNFALVGVGVGYPKLGLRAMVVVS...,71.119,71.119,66.449,226,24815.6064,0.097345,27.871239,...,0.146607,0.072872,-0.037738,0.250836,-0.018934,0.043748,0.107054,-0.144702,0.063847,-0.135173
2,>1186315,79.991,MGRDLFSGPVPVLVLMLGSVDGARFAVLGVGVGYARLGFQAILAVF...,80.665,80.665,79.991,226,24698.3030,0.097345,50.903097,...,-0.043685,0.027612,-0.064697,0.138363,0.013731,0.021259,-0.000714,-0.005943,-0.009956,-0.050849
3,>1828763,75.787,MGSSLFEGEVPVLVLALGDVDGRRFAVAGVGVGHRREGLLVAVLVA...,81.485,81.485,75.787,226,24398.0035,0.092920,31.591593,...,0.053924,0.074759,-0.058464,0.146572,0.012798,0.041014,0.039836,-0.031868,0.053415,-0.015060
4,>1283538,78.792,MGADLLSGPVPVLVALLGDADGARFAVLGAGVGFARRGLLVLLAVN...,80.615,80.615,78.792,226,24173.8532,0.084071,31.789381,...,0.014999,0.042315,-0.034835,0.099143,0.018207,0.066471,0.042846,-0.021110,0.029446,-0.062992
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9994,>104179,46.098,DAGRALLAGDVPLRVEAKGNVNGKEFEIVGEGVGNAQRGELRAVYT...,54.542,54.542,46.098,342,37383.4999,0.067251,28.543012,...,0.078056,0.038029,-0.040128,0.007463,0.001547,-0.056949,0.073136,0.001345,-0.038258,0.050697
9995,>123312,54.889,AAGRALLAGPTPVRHRMRGDVNGKKFEVEGEGVGDAQTGRQRMTYT...,63.491,63.491,54.889,342,37418.8110,0.067251,35.971053,...,0.043406,0.004319,-0.047475,0.010665,-0.016419,-0.038964,0.096877,-0.016057,-0.033251,0.048270
9996,>124303,48.480,SEGHALLAGPVPVEVHLKGNVNGREFEIRGEGVGDARTGRLSLLFT...,54.602,54.602,48.480,342,37512.7351,0.067251,37.542105,...,0.090486,0.046885,-0.081142,0.003365,-0.015695,-0.056584,0.078088,-0.015728,-0.004072,0.011623
9997,>140046,46.693,SDGRALLADPTPVRTRMKGNVNGLEFEIEGEGVGDARTGRLEMTYV...,54.438,54.438,46.693,342,37703.8657,0.070175,38.214912,...,0.086514,0.028280,-0.017121,0.001272,-0.020815,-0.033356,0.100702,-0.002994,-0.050231,0.039036
9998,>146150,47.444,SEGRKLLEGDVPLRVRLDGDVNGKRFRVEGEGVGNAQTGTQELRFV...,55.583,55.583,47.444,342,37511.5819,0.055556,34.643860,...,0.068985,0.030060,-0.081049,0.015295,-0.012021,-0.050009,0.073071,0.007069,-0.005548,0.043196

In [44]:
data = data.drop(['seq_ID', 'Sequence'], axis = 1)
data

,SER,EMB2,AAC,EMB,seq_len,molecular_weight,aromaticity,instability_index,isoelectric_point,gravy,...,emb_1270,emb_1271,emb_1272,emb_1273,emb_1274,emb_1275,emb_1276,emb_1277,emb_1278,emb_1279
0,77.974,80.157,80.157,77.974,226,24871.5782,0.106195,32.226106,5.254333,0.221681,...,0.109929,0.073005,0.008115,0.122912,-0.006657,0.111748,0.052604,-0.048403,0.067519,-0.084471
1,66.449,71.119,71.119,66.449,226,24815.6064,0.097345,27.871239,6.850997,0.058407,...,0.146607,0.072872,-0.037738,0.250836,-0.018934,0.043748,0.107054,-0.144702,0.063847,-0.135173
2,79.991,80.665,80.665,79.991,226,24698.3030,0.097345,50.903097,4.979744,0.193805,...,-0.043685,0.027612,-0.064697,0.138363,0.013731,0.021259,-0.000714,-0.005943,-0.009956,-0.050849
3,75.787,81.485,81.485,75.787,226,24398.0035,0.092920,31.591593,5.963911,0.269469,...,0.053924,0.074759,-0.058464,0.146572,0.012798,0.041014,0.039836,-0.031868,0.053415,-0.015060
4,78.792,80.615,80.615,78.792,226,24173.8532,0.084071,31.789381,5.940550,0.307080,...,0.014999,0.042315,-0.034835,0.099143,0.018207,0.066471,0.042846,-0.021110,0.029446,-0.062992
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9994,46.098,54.542,54.542,46.098,342,37383.4999,0.067251,28.543012,5.313218,-0.416667,...,0.078056,0.038029,-0.040128,0.007463,0.001547,-0.056949,0.073136,0.001345,-0.038258,0.050697
9995,54.889,63.491,63.491,54.889,342,37418.8110,0.067251,35.971053,5.622650,-0.392982,...,0.043406,0.004319,-0.047475,0.010665,-0.016419,-0.038964,0.096877,-0.016057,-0.033251,0.048270
9996,48.480,54.602,54.602,48.480,342,37512.7351,0.067251,37.542105,5.512950,-0.418129,...,0.090486,0.046885,-0.081142,0.003365,-0.015695,-0.056584,0.078088,-0.015728,-0.004072,0.011623
9997,46.693,54.438,54.438,46.693,342,37703.8657,0.070175,38.214912,5.046530,-0.477778,...,0.086514,0.028280,-0.017121,0.001272,-0.020815,-0.033356,0.100702,-0.002994,-0.050231,0.039036
9998,47.444,55.583,55.583,47.444,342,37511.5819,0.055556,34.643860,5.140143,-0.446199,...,0.068985,0.030060,-0.081049,0.015295,-0.012021,-0.050009,0.073071,0.007069,-0.005548,0.043196

In [45]:
res = model_cl_extra.predict_proba(data)
res = pd.DataFrame(res)
res[1]

0       0.617333
1       0.594000
2       0.624000
3       0.596667
4       0.594667
          ...
9994    0.540000
9995    0.549333
9996    0.549333
9997    0.574667
9998    0.571333
Name: 1, Length: 9999, dtype: float64

In [46]:
final_res = pd.read_csv('../therm/top_brightness.csv')
final_res

,Unnamed: 0,id,struct,brightness,sequence
0,6808718,1379211,"avGFP_2WUR,",5.406,MGRDLFAGEVPVLVLMVGNVDGANFAIAGVGFGDARRGLLVLLAVA...
1,7285095,1855588,"EGFP_4EUL,",5.240,MGRELFEGLRPVLVVMKGSVDGKNFALVGVGVGYPKLGLRAMVVVS...
2,6615822,1186315,"avGFP_2WUR,",5.170,MGRDLFSGPVPVLVLMLGSVDGARFAVLGVGVGYARLGFQAILAVF...
3,7258270,1828763,"EGFP_4EUL,",5.100,MGSSLFEGEVPVLVLALGDVDGRRFAVAGVGVGHRREGLLVAVLVA...
4,6713045,1283538,"avGFP_2WUR,",5.086,MGADLLSGPVPVLVALLGDADGARFAVLGAGVGFARRGLLVLLAVN...
...,...,...,...,...,...
9995,2032812,123312,"vsfGFP-0_4PFE,",3.533,AAGRALLAGPTPVRHRMRGDVNGKKFEVEGEGVGDAQTGRQRMTYT...
9996,2033803,124303,"vsfGFP-0_4PFE,",3.533,SEGHALLAGPVPVEVHLKGNVNGREFEIRGEGVGDARTGRLSLLFT...
9997,2049546,140046,"vsfGFP-0_4PFE,",3.533,SDGRALLADPTPVRTRMKGNVNGLEFEIEGEGVGDARTGRLEMTYV...
9998,2055650,146150,"vsfGFP-0_4PFE,",3.533,SEGRKLLEGDVPLRVRLDGDVNGKRFRVEGEGVGNAQTGTQELRFV...
9999,2063591,154091,"vsfGFP-0_4PFE,",3.533,EEGRKLLAGPVPIRVEMEGDVNGKKFKIEGEGVGDAQTGTLEQRYV...

In [48]:
final_res['therm'] = res[1]
final_res

,Unnamed: 0,id,struct,brightness,sequence,therm
0,6808718,1379211,"avGFP_2WUR,",5.406,MGRDLFAGEVPVLVLMVGNVDGANFAIAGVGFGDARRGLLVLLAVA...,0.617333
1,7285095,1855588,"EGFP_4EUL,",5.240,MGRELFEGLRPVLVVMKGSVDGKNFALVGVGVGYPKLGLRAMVVVS...,0.594000
2,6615822,1186315,"avGFP_2WUR,",5.170,MGRDLFSGPVPVLVLMLGSVDGARFAVLGVGVGYARLGFQAILAVF...,0.624000
3,7258270,1828763,"EGFP_4EUL,",5.100,MGSSLFEGEVPVLVLALGDVDGRRFAVAGVGVGHRREGLLVAVLVA...,0.596667
4,6713045,1283538,"avGFP_2WUR,",5.086,MGADLLSGPVPVLVALLGDADGARFAVLGAGVGFARRGLLVLLAVN...,0.594667
...,...,...,...,...,...,...
9995,2032812,123312,"vsfGFP-0_4PFE,",3.533,AAGRALLAGPTPVRHRMRGDVNGKKFEVEGEGVGDAQTGRQRMTYT...,0.549333
9996,2033803,124303,"vsfGFP-0_4PFE,",3.533,SEGHALLAGPVPVEVHLKGNVNGREFEIRGEGVGDARTGRLSLLFT...,0.549333
9997,2049546,140046,"vsfGFP-0_4PFE,",3.533,SDGRALLADPTPVRTRMKGNVNGLEFEIEGEGVGDARTGRLEMTYV...,0.574667
9998,2055650,146150,"vsfGFP-0_4PFE,",3.533,SEGRKLLEGDVPLRVRLDGDVNGKRFRVEGEGVGNAQTGTQELRFV...,0.571333
9999,2063591,154091,"vsfGFP-0_4PFE,",3.533,EEGRKLLAGPVPIRVEMEGDVNGKKFKIEGEGVGDAQTGTLEQRYV...,NaN

In [51]:
final_res.sort_values('therm', ascending=False)

,Unnamed: 0,id,struct,brightness,sequence,therm
6570,7307727,1878220,"EGFP_4EUL,",3.613,MGSELLEKVVPVLVLAKGNVDGNNFSIAGVGFGHAKKGLLVLLLIS...,0.700667
7451,6693124,1263617,"avGFP_2WUR,",3.590,MGRELFTGPVPVLVLLNGNVDGKKFSILGVGFCYPVRGLRLLLLIS...,0.694667
8515,6586974,1157467,"avGFP_2WUR,",3.564,MGRDLLEGPVPLLSLLYGNVNGKNFAILGAGVGLAPRGLSLMLFIS...,0.693333
613,6795304,1365797,"avGFP_2WUR,",4.094,MGSDLFSGPVPVLTLLIGNFDGKRFAILGVGVCIARLGLQVVVYVS...,0.692000
748,7055029,1625522,"EGFP_4EUL,",4.055,MGRELLEGPVPVAVLMYGNIDGKKFAIAGAGVGVAREGLLALHLVS...,0.690000
...,...,...,...,...,...,...
8941,2514543,605043,"AausFP1_6S67,",3.555,LFAAPFPLRVDMTLDVEGKRARIRGEGTGDAATGRVRAHFVCTTGE...,0.485333
3467,2665901,756401,"AausFP1_6S67,",3.736,LFAQPFPLRVDMELDVEGKRARIVGEGTGDAATGRVRARYTCTTGK...,0.483333
8420,2754952,845452,"AausFP1_6S67,",3.566,LFAERFPLRVRMELDIEGKKAKIEGEGWGDANTGEVEAHFVCTTGK...,0.482000
8320,2775858,866358,"AausFP1_6S67,",3.568,LFAEPFPVRVRMKGDVEGKKFEIVGEGTGDARTGEVRLHYVCTTGE...,0.480667
9999,2063591,154091,"vsfGFP-0_4PFE,",3.533,EEGRKLLAGPVPIRVEMEGDVNGKKFKIEGEGVGDAQTGTLEQRYV...,NaN

In [52]:
final_res.to_csv('../therm/final_res.csv', index=False)